resolver: lts-7.14
packages:
- .
- location:
    git: https://github.com/serokell/universum
    commit: 32316939cd9239fc283d4d562508e67767020fcf
  extra-dep: true
nix:
  shell-file: shell.nix
extra-deps:
- orgmode-parse-0.1.1.3
flags: {}
extra-package-dbs: []
