resolver: lts-7.14

packages:
- .
- location:
    git: https://github.com/serokell/universum
    commit: 32316939cd9239fc283d4d562508e67767020fcf
  extra-dep: true
- location:
    git: https://github.com/serokell/log-warper.git
    commit: e05d74587ff9270891a3e57f1f15d9e91c8d2c83
  extra-dep: true

nix:
  shell-file: shell.nix

extra-deps:
- orgmode-parse-0.1.1.3
- serokell-util-0.1.3.0
- aeson-extra-0.4.0.0
- data-msgpack-0.0.8
- time-units-1.0.0
- recursion-schemes-5.0.1
